---
## Identifiant pour la webUI de qBittorrent :

qbt_log:
  qbt_host: "localhost:8080"
  qbt_user: "admin"
  qbt_pass: "adminadmin"

##
##    /!\ Configuration de la méthode de controle de l'espace disque et déclanchement de la suppréssion /!\
##    /!\ Seul True n'est disponible si vous utilisé ce script pour une instance distante (ex: Seedbox) /!\
##
##    True = Déclanchement de la suppréssion quand il ne reste que xx GiB d'espace libre sur votre disque
##    False = Déclanchement de la suppréssion quand vous dépassé XX % d'espace disque
##

ControlMethode: True # True or False

## Pourcentage d'espace disque qui déclenche la suppression des torrents et path du disque a surveillé. 
## Si ControlMethode = False

diskUsageByPercent:
  max: 80
  path: './'

## Qantité d'espace disque restante qui déclenche la suppression des torrents.
## Si ControlMethode = True

diskUsageByGiB:
  val: 100

## Intervalle entre les exécutions du programme en minute

interval: 10

## Paramètres pour le tri et la sélection des torrents à supprimer en priorité :

t_statistique:
  min_SeedTime: 80 # A exprimer en heures
  min_Ratio: 0 # Ratio O = null

# Les Tags aka étiquette (dans qBt) qui permettrons de faire passer un torrent en priorité, de le favoriser ou de l'exlure.

t_tags:
  priority:
    - "PUBLIC"
    - "TODELT"
  prefer:
    - "YGG"
    - "CASA"
  exclud:
    - "DONOT"
    - "PERSO"
  states:
    - "checkingDL"
    - "allocating"
    - "checkingResumeData"
    - "downloading"
    - "metaDL"
    - "moving"