---
## Identifiant pour la webUI de qBittorrent :

qbt_log:
  qbt_host: "localhost:8080"
  qbt_user: "admin"
  qbt_pass: "adminadmin"

## Pourcentage d'espace disque qui déclenche la suppression des torrents :

disk:
  MAX: 80
  PATH: './'

## Intervalle entre les exécutions du programme en minute

interval: 10

## Paramètres pour le tri et la sélection des torrents à supprimer en priorité :

t_statistique:
  min_SeedTime: 80 # A exprimer en heures
  min_Ratio: 0 # Ratio O = null

# Les Tags aka étiquette (dans qBt) qui permettrons de faire passer un torrent en priorité, de le favoriser ou de l'exlure.

t_tags:
  priority:
    - "PUBLIC"
    - "TODELT"
  prefer:
    - "YGG"
    - "CASA"
  exclud:
    - "DONOT"
    - "PERSO"
  states:
    - "checkingDL"
    - "allocating"
    - "checkingResumeData"
    - "downloading"
    - "metaDL"
    - "moving"